// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using croupe_06_TournoiGolf.Data;

#nullable disable

namespace croupe_06_TournoiGolf.Data.Migrations
{
    [DbContext(typeof(GolfDbContext))]
    [Migration("20260412031327_InitialEfCoreSchema")]
    partial class InitialEfCoreSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("croupe_06_TournoiGolf.Models.Commandite", b =>
                {
                    b.Property<int>("CommanditeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommanditeId"));

                    b.Property<string>("Commentaire")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TournoiId")
                        .HasColumnType("int");

                    b.Property<string>("TypeCommandite")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("CommanditeId");

                    b.HasIndex("TournoiId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Commandites");
                });

            modelBuilder.Entity("croupe_06_TournoiGolf.Models.Equipe", b =>
                {
                    b.Property<int>("EquipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipeId"));

                    b.Property<string>("CodeSecret")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreeParUtilisateurId")
                        .HasColumnType("int");

                    b.Property<int>("NbJoueursMax")
                        .HasColumnType("int");

                    b.Property<string>("NomEquipe")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("TournoiId")
                        .HasColumnType("int");

                    b.HasKey("EquipeId");

                    b.HasIndex("CodeSecret")
                        .IsUnique()
                        .HasDatabaseName("IX_Equipes_CodeSecret");

                    b.HasIndex("CreeParUtilisateurId");

                    b.HasIndex("TournoiId");

                    b.ToTable("Equipes");
                });

            modelBuilder.Entity("croupe_06_TournoiGolf.Models.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<int?>("CommanditeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("EquipeId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontantPaye")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Prenom")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("StatutInscription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TournoiId")
                        .HasColumnType("int");

                    b.Property<string>("TypeParticipant")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("ParticipantId");

                    b.HasIndex("CommanditeId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("TournoiId", "UtilisateurId")
                        .HasDatabaseName("IX_Participants_TournoiId_UtilisateurId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("croupe_06_TournoiGolf.Models.Tournoi", b =>
                {
                    b.Property<int>("TournoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournoiId"));

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreeLe");

                    b.Property<DateTime?>("DateLimiteInscription")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateTournoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("InscriptionsOuvertes")
                        .HasColumnType("bit");

                    b.Property<string>("Lieu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NbEquipesMax")
                        .HasColumnType("int")
                        .HasColumnName("NbEquipesMax");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PlacesParticipantsMax")
                        .HasColumnType("int")
                        .HasColumnName("PlacesParticipantsMax");

                    b.HasKey("TournoiId");

                    b.ToTable("Tournois");
                });

            modelBuilder.Entity("croupe_06_TournoiGolf.Models.Utilisateur", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilisateurId"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("MotDePasseHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NomEntreprise")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("UtilisateurId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Utilisateurs_Email");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("croupe_06_TournoiGolf.Models.Commandite", b =>
                {
                    b.HasOne("croupe_06_TournoiGolf.Models.Tournoi", "Tournoi")
                        .WithMany()
                        .HasForeignKey("TournoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("croupe_06_TournoiGolf.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournoi");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("croupe_06_TournoiGolf.Models.Equipe", b =>
                {
                    b.HasOne("croupe_06_TournoiGolf.Models.Utilisateur", "Createur")
                        .WithMany()
                        .HasForeignKey("CreeParUtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("croupe_06_TournoiGolf.Models.Tournoi", "Tournoi")
                        .WithMany()
                        .HasForeignKey("TournoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Createur");

                    b.Navigation("Tournoi");
                });

            modelBuilder.Entity("croupe_06_TournoiGolf.Models.Participant", b =>
                {
                    b.HasOne("croupe_06_TournoiGolf.Models.Commandite", "Commandite")
                        .WithMany("Participants")
                        .HasForeignKey("CommanditeId");

                    b.HasOne("croupe_06_TournoiGolf.Models.Tournoi", "Tournoi")
                        .WithMany()
                        .HasForeignKey("TournoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("croupe_06_TournoiGolf.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId");

                    b.Navigation("Commandite");

                    b.Navigation("Tournoi");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("croupe_06_TournoiGolf.Models.Commandite", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
