flowchart TB
    U[Utilisateur participant] --> UI
    A[Administrateur] --> UI
    C[Commanditaire] --> UI

    subgraph UI[Couche presentation]
        V1[Views Razor]
        S1[Session HTTP]
        W[wwwroot CSS JS Images]
    end

    subgraph APP[Couche application MVC]
        H[HomeController]
        AU[AuthController]
        T[TournoiController]
        I[InscriptionController]
        E[EquipeController]
        CO[CommanditeController]
        AD[AdminController]
        B[BaseController]
    end

    subgraph METIER[Couche metier / services]
        PH[IPasswordHasher / PasswordHasher]
        REGLES[Regles metier\nconnexion\nroles\ninscription\npaiement simule\ngestion equipe]
    end

    subgraph DONNEES[Couche donnees]
        DBCTX[GolfDbContext]
        M1[Utilisateur]
        M2[Tournoi]
        M3[Participant]
        M4[Equipe]
        M5[Commandite]
    end

    SQL[(SQL Server)]
    FS[(Stockage fichiers\nwwwroot/images/tournois)]

    UI --> APP
    APP --> S1
    APP --> PH
    APP --> REGLES
    APP --> DBCTX
    DBCTX --> M1
    DBCTX --> M2
    DBCTX --> M3
    DBCTX --> M4
    DBCTX --> M5
    DBCTX --> SQL
    T --> FS

    AU --> PH
    AU --> DBCTX
    T --> DBCTX
    I --> DBCTX
    E --> DBCTX
    CO --> DBCTX
    AD --> DBCTX
    B --> S1
